### ISSUE TITLE
Tables: De-Selecting with "select all" checkbox leaves hidden items selected

### ISSUE THREAD

**Issue by Clairebaer** [devmount/sales#36]
**Describe the bug**
If all elements deselected by unchecking the "select all" checkbox, all hidden elements remain selected.

**To Reproduce**

1. Go to Customer.
2. Click on select all.
3. Choose a filter to hide some elements.
4. Deselect all.
5. Clear filter.

**Expected behavior**
All elements, whether hidden or not, are deselected.

**Comment by devmount** [comment]
Good catch, I'll take a look at this.

**Comment by devmount** [comment]
This got fixed with the current Filament version, can't reproduce the described behavior anymore. Setting a filter now always results in all checkboxes getting unchecked.
