### ISSUE TITLE
Contact Customer: Error if no mailadress is filed

### ISSUE THREAD

**Issue by Clairebaer** [devmount/sales#37]
**Describe the bug**
If no mailadress is filed for a customer, it is still possible to use "Contact customer" in the addional menu (three dots). When trying to send the message, an error shows: 
Symfony \ Component \ Mime \ Exception \ LogicException
PHP 8.3.4
11.2.0
An email must have a "To", "Cc", or "Bcc" header.

**To Reproduce**

1. Go to Customers.
2. Click on the additional menu of one customer.
3. Select "Contact Customer".
4. Fill out "subject".
5. Click "Send".
6. See error.

**Expected behavior**

If no mailadress is filed, 
1. the option "Contact customer" is not available.
or
2. the user is noticed about the missing mailadress with the possibiliy to provide one.

**Screenshots**
![Contact-customer-without-mailadress](https://github.com/devmount/sales/assets/64353037/62731362-4d13-42a3-a4c5-8a9790dadcb5)

**Comment by devmount** [comment]
Good catch, I'll see if there's a way to gray out that option and giving a hint, that no email address was given (on mouse hover or tap, e.g.).
