### ISSUE TITLE
Customers \ Add new Customer: unexpected behaviour of "Cancel" button

### ISSUE THREAD

**Issue by Clairebaer** [devmount/sales#39]
**Describe the bug**
Customers Overview -> New Customer -> Cancel Button does not go back to overview, instead switches between saved new customer and empty form

**To Reproduce**

1. Go to Customers
2. Click on "Add Customer", fill out necessary entries
3. Save with "Save and add customer"
4. Click on "Cancel" -> Form switches back to Customer 1
5. Click on "Cancel" -> Form switches to empty form
6. Step 4 & 5 can be repeated without returning to the Overview

**Expected behavior**
Click on "Cancel" returns to overview.

**Screenshots**

**System (please complete the following information):**

- Sales version: 2.1.8

**Comment by Clairebaer** [comment]
Not reproducible in 2.1.9

**Comment by devmount** [comment]
Good catch. It bothered me some time now that some Cancel buttons were somehow actually Back buttons to the previous page (even if that was the same page after saving). In 2.1.9 the cancel button goes back to the overview page?

**Comment by Clairebaer** [comment]
yes, now it works as expected :)

**Comment by devmount** [comment]
Nice, might have been fixed by #32. Thanks for testing!
