### ISSUE TITLE
Projects \ Create offer: PDF is not downloaded

### ISSUE THREAD

**Issue by Clairebaer** [devmount/sales#40]
**Describe the bug**
No PDF is downloaded.

**To Reproduce**

1. Go to Projects
2. Click on one project.
3. Scroll down to Click on "Offer (PDF)".
4. A new tab opens and closes without any download.

**Expected behavior**
The offer (PDF) is downloaded automatically or a new tab opens to download the PDF.

**System (please complete the following information):**

- version: 2.19

**Additional information**
The same problem occurs with downloading invoices: For a finished project with an existing invoice I can download it without problems. If I modify anything, the above decribed behaviour shows.

**Comment by devmount** [comment]
Does your test project have any estimation entries? I suspect, the offer PDF generation currently only works for projects with at least one estimation record:

![image](https://github.com/devmount/sales/assets/5441654/3c3acbb1-ecf3-4fe1-aa04-c938d616d06e)

**Comment by Clairebaer** [comment]
You are right, that was it. So today I tried one with estimates ("Projekt // Test") and a download tab opens but without downloading. 
![grafik](https://github.com/devmount/sales/assets/64353037/31bbe097-4caa-4029-bd4b-7827ef072057)

Interestingly, for the example project in your screenshot, I can download an offer :D so I tried making my testproject as similar as possible but nothing changed.
