### ISSUE TITLE
PDF offer: end of project period is a fix number

### ISSUE THREAD

**Issue by Clairebaer** [devmount/sales#49]
**Describe the bug**
In the PDF offer the delivery period of the project ends with 1970 instead of the filed due date.

**To Reproduce**
Create a pdf offer in a project.
Scroll to "Leistungszeitraum".

**Expected behavior**
The delivery period of the project ends with the due date taht is filed in the project.

**Screenshots**
![62_offer_eop](https://github.com/devmount/sales/assets/64353037/e86ef60d-df95-43cf-b70e-0c1acd90026f)

**System (please complete the following information):**

- version: 2.1.10

**Additional context**
This problem was seen for exiting projects ('Dolorum Cumque Quia') and also for changed projects ('Enim Quasi Fugit').

**Comment by devmount** [comment]
Ah good old start of the 32bit unix time epoch 😂 Good catch, thanks.
